mac_task:
  auto_cancellation: true
  name: macos 3.6 conda4.8.1
  osx_instance:
    image: catalina-xcode
  env:
    PATH: $HOME/conda/bin:$PATH
  conda_script:
    - xcode-select -p
    - clang --version
    - ls /Applications/Xcode-11.3.1.app/Contents/Developer
    - ls /Applications/Xcode*
    - ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
    - ls /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/
    # - brew install llvm
    # sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/* /usr/local/include/
    - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > install.sh
    - bash install.sh -b -p $HOME/conda
    # https://github.com/napari/napari/pull/594#issuecomment-542475164
    - conda install --yes -c conda-forge setuptools
    - conda install -yn base conda=4.8.1
    - conda install -y python=3.6
    - rm install.sh

  pip_cache:
    folder: $HOME/Library/Caches/pip
    populate_script: 
      - python -m pip install --retries 3 --upgrade pip
      - pip install -r requirements.txt

  install_script: python setup.py develop
  check_script: python -c "import napari; print(napari.__version__)"
