mac_task:
  auto_cancellation: true
  name: macos 3.6 conda4.8.1
  osx_instance:
    image: catalina-xcode
  env:
    PATH: $HOME/conda/bin:$PATH
  conda_script:
    # - brew install llvm
    - echo $CXXFLAGS
    # - export CXXFLAGS="-stdlib=libc++"
    # - export CFLAGS="-stdlib=libc++"
    - export MACOSX_DEPLOYMENT_TARGET=10.10
    - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > install.sh
    - bash install.sh -b -p $HOME/conda
    # https://github.com/napari/napari/pull/594#issuecomment-542475164
    - conda install --yes -c conda-forge setuptools
    - conda install -yn base conda=4.8.1
    - conda install -y python=3.6

  pip_script:
    # - sudo pip install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib"
    - python -m pip install --retries 3 --upgrade pip
    - pip install -r requirements.txt

  install_script: python setup.py develop
  check_script: python -c "import napari; print(napari.__version__)"
