mac_task:
  auto_cancellation: true

  matrix:
    env:
      matrix:
        PY_VER: "3.6"

  name: macos ${PY_VER}
  osx_instance:
    image: catalina-xcode
  env:
    PATH: $HOME/conda/bin:$PATH
  conda_script:
    - export MACOSX_DEPLOYMENT_TARGET=10.10
    - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > install.sh
    - bash install.sh -b -p $HOME/conda
    # https://github.com/napari/napari/pull/594#issuecomment-542475164
    - conda install --yes -c conda-forge setuptools
    - conda update -yn base conda
    - conda install -y python=$PY_VER
    - rm install.sh

  pip_cache:
    folder: $HOME/Library/Caches/pip
    populate_script:
      - export MACOSX_DEPLOYMENT_TARGET=10.10
      - python -m pip install --retries 3 --upgrade pip
      - pip install -r requirements.txt

  install_script:
    - python -m pip install --retries 3 --upgrade pip
    - pip install --retries 3 -r requirements.txt
    - python setup.py develop

  check_script: python -c "import napari; import numpy; print(napari.__version__)"

  test_script: pytest -v
