name: CI
# on:
#   pull_request:
#   push:
#     branches:
#       - master

on: [push, pull_request]

jobs:
  pretest:
    name: Pre-test checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [flake8, black]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Run pre-test check
        run: |
          tox -e ${{ matrix.task }}

  linux:
    # Only run this and subsequent steps on branches.
    # `github.head_ref` only exists on pull requests.
    # if: github.head_ref
    name: Linux ${{ matrix.python-version }}
    needs: pretest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
    env:
      DISPLAY: ':99.0'
      PYVER: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install libxkbcommon-x11-0
          /sbin/start-stop-daemon --start --quiet \
            --pidfile /tmp/custom_xvfb_99.pid --make-pidfile \
            --background --exec /usr/bin/Xvfb \
            -- :99 -screen 0 1920x1200x24 -ac +extension GLX
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Test
        run: tox -e py${PYVER//.}-pyqt,py${PYVER//.}-pyside -- --cov-report=xml --cov=napari
      - name: Coverage
        if: matrix.python-version == '3.8'
        uses: codecov/codecov-action@v1

  windows:
    name: Windows 3.8
    runs-on: windows-latest
    needs: pretest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Test
        run: tox -e py38-pyside -- -o qt_no_exception_capture=1

  mac:
    name: Mac 3.8
    runs-on: macos-latest
    needs: pretest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Test
        run: tox -e py38-pyqt,py38-pyside
