name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"os\":[\"ubuntu-latest\", \"windows-latest\", \"macos-latest\"]}"

  job2:
    needs: job1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo "hi"
