name: CI
# on:
#   pull_request:
#   push:
#     branches:
#       - master

on: [push, pull_request]

jobs:
  pretest:
    name: Pre-test checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [flake8, black]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Run pre-test check
        run: |
          tox -e ${{ matrix.task }}

  linux:
    # Only run this and subsequent steps on branches.
    # `github.head_ref` only exists on pull requests.
    # if: github.head_ref
    name: Linux ${{ matrix.python-version }}
    needs: pretest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install xvfb
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Test
        run: xvfb-run --auto-servernum tox
      - name: Coverage
        if: matrix.python-version == '3.8'
        uses: codecov/codecov-action@v1

  mac_windows:
    name: ${{ matrix.platform }} 3.8
    runs-on: ${{ matrix.platform }}
    needs: pretest
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools tox
      - name: Test
        run: tox ${{ runner.os == 'Windows' && '-- -o qt_no_exception_capture=1' || '' }}
